### ISSUE TITLE
how up-to-date is this test suite to the updated spec?

### ISSUE THREAD

**Issue by haoyuanli** [ga4gh-rnaseq/rnaget-compliance-suite#18]
i assume changes that were made to the specs are not reflected here yet

PS.
I looked around, it looks like the test suite is pretty much not related to the spec versioned at 1.0.0

**Comment by jb-adams** [comment]
Hi @haoyuanli,

We've just merged the new compliance version with the master branch. The tests now reflect the latest updates to the [RNAget spec](https://github.com/ga4gh-rnaseq/schema/blob/master/rnaget-openapi.yaml)

**Comment by haoyuanli** [comment]
Cool, thanks. It's a big change!

Thanks again
