### ISSUE TITLE
double slashes for the */filters endpoints

### ISSUE THREAD

**Issue by haoyuanli** [ga4gh-rnaseq/rnaget-compliance-suite#20]
I notice that the test suites test "projects//filters", instead of "projects/filters"

i look at all other tests, this is the only one that has prepending slash.

I proposed a fix below

https://github.com/ga4gh-rnaseq/rnaget-compliance-suite/pull/21

**Comment by haoyuanli** [comment]
BTW - the problem is here

![image](https://user-images.githubusercontent.com/18109953/70941115-9e87a500-2000-11ea-9258-e354c6f3b92b.png)

under test.py, it seem enough to just do `"url": c.PROJECT_API + "filters"`

**Comment by haoyuanli** [comment]
i have made a PR here that should solve the issue

https://github.com/ga4gh-rnaseq/rnaget-compliance-suite/pull/21

@saupchurch @jb-adams can one of you kindly take a look? Thanks

**Comment by jb-adams** [comment]
Thanks @haoyuanli, I've merged your changes to master. Can we close this?

**Comment by haoyuanli** [comment]
sure
